/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gsralex.gflow.core.thriftgen.scheduler;


public enum JobStatus implements org.apache.thrift.TEnum {
  SENDOK(1),
  SENDERR(2),
  EXECUTEOK(3),
  EXECUTEERR(4);

  private final int value;

  private JobStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JobStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return SENDOK;
      case 2:
        return SENDERR;
      case 3:
        return EXECUTEOK;
      case 4:
        return EXECUTEERR;
      default:
        return null;
    }
  }
}
