package com.gsralex.gflow.core.thrift;

/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum TJobStatus implements org.apache.thrift.TEnum {
  OK(0),
  ERROR(2);

  private final int value;

  private TJobStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TJobStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 2:
        return ERROR;
      default:
        return null;
    }
  }
}
