/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gsralex.gflow.pub.thriftgen.scheduler;


public enum GroupStatus implements org.apache.thrift.TEnum {
  EXECUTING(1),
  PAUSE(2),
  STOP(3),
  FINISH(4);

  private final int value;

  private GroupStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GroupStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return EXECUTING;
      case 2:
        return PAUSE;
      case 3:
        return STOP;
      case 4:
        return FINISH;
      default:
        return null;
    }
  }
}
